### PR TITLE
More tweaks for TypeScript bindings

### PR DESCRIPTION
**Pull request by Blaizer**
Sorry if I'm spamming pull requests but here's a couple more small changes that help ease development in TypeScript. Not 100% sure if I went the best way about all of this, so I'm open to discussion.

### CODE REVIEW

**Comment by lixw1994** [comment]
- Thanks for your work!
-  `MatchData.data: any` will be better.
- But [in nakama doc](https://heroiclabs.com/docs/gameplay-multiplayer-realtime/#send-data-messages),  **To identify each message as a specific "command" it contains an Op code as well as the payload**. So IMO, **MatchData** options is required.

**Comment by lixw1994** [comment]
- [Nakama doc](https://heroiclabs.com/docs/gameplay-multiplayer-realtime/#send-data-messages) said that **To identify each message as a specific "command" it contains an Op code as well as the payload**. So IMO, **MatchData** options will be better required.

**Comment by Blaizer** [comment]
Sending `presence` in MatchDataSend is definitely optional, because the docs don't even mention you can specify that. Making just that optional is possible I think it would look something like this:
```
export interface MatchDataSend {
    match_data_send: Omit<MatchData, 'presence'> & { presence?: Presence };
}
```

But that's almost as bad as just writing out the type in full.

**Comment by Blaizer** [comment]
Actually, I found a much better way:

```
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
type PartialKeys<T, K extends keyof T> = Omit<T, K> & Pick<Partial<T>, K>;

export interface MatchDataSend
{
    match_data_send: PartialKeys<MatchData, 'presence'>;
}
```

If we require Typescript 3.5 then Omit is part of the standard library. I'm happy to make this change if there's no objections?

**Comment by novabyte** [comment]
@Blaizer I'm happy for the client sdk to adopt TypeScript 3.5 as the minimum required version. What do you think @lixw1994?

**Comment by lixw1994** [comment]
@novabyte I'm happy too!

**Comment by Blaizer** [comment]
Thanks, the changes have been made.

**Comment by novabyte** [comment]
@Blaizer My TypeScript is rusty but I think this looks good. 👍

**Pull request merged**
