### PR TITLE
build facebook instant games API

### PR DESCRIPTION
**Pull request by lugehorsam**
Builds and bundles changes made to support the Facebook Instant Games API. Closes https://github.com/heroiclabs/nakama-js/issues/61

@novabyte @leoncarl

### CODE REVIEW

**Comment by novabyte** [comment]
@lugehorsam We'll need to add the wrapper method for it to the `Client` type. For example:

https://github.com/heroiclabs/nakama-js/blob/master/src/client.ts#L1180

**Comment by lugehorsam** [comment]
@novabyte added. I am also going to see if there is a way to write tests for this.

**Comment by novabyte** [comment]
@lugehorsam That would be great but we'll need to keep the current method signatures around for backwards compatibility.

**Comment by lugehorsam** [comment]
@novabyte tests added, rdy for review.

**Comment by novabyte** [comment]
@lugehorsam Nice one. Looks good to me 👍

**Comment by lugehorsam** [comment]
@leoncarl merged!

**Pull request merged**
