### PR TITLE
Socket pb docs

### PR DESCRIPTION
**Pull request by attackgoat**
I noticed the docs were not up to date on this topic, so I made some adjustments. I also put a second commit in there trying to make the document more palatable.

HTH! 😄

### CODE REVIEW

**Comment by lugehorsam** [comment]
Thank you for the contribution @attackgoat!

It mostly looks good though we may want to still mention the existence of the protobuf adapter in the `nakama-js` workspace readme, perhaps with a link. But agreed that we don't need the full example in that readme.

**Comment by attackgoat** [comment]
I can add that, sound good?

**Comment by lugehorsam** [comment]
@attackgoat yep!

**Comment by lugehorsam** [comment]
👍 thanks @attackgoat

**Pull request merged**
